### ISSUE TITLE
Add previews and releases to the repo

### ISSUE THREAD

**Issue by monkeyK1n9** [YBTopaz8/Dimmer-MAUI#29]
## Add a preview to the repo:

We can add previews to the repo. This can be two or three screenshots of the app on different platforms to showcase the "crossplatform" aspect of MAUI.

## Add a release:

We can add release candidate 0.0.1 or something similar. This should be a build or executable which someone can download to try the app.

**Comment by YBTopaz8** [comment]
There is a release for Windows and Android is coming this weeked 🙂
