### ISSUE TITLE
Add the possibitity to run one music more than one Time.

### ISSUE THREAD

**Issue by Ngnintedem3004** [YBTopaz8/Dimmer-MAUI#63]
we Can enable to a user the possibilty to run a music one Time , 2 Times 3 Times etc...

**Comment by YBTopaz8** [comment]
Meaning you'd like to have something like 
- click a button "Play x times"
- enter the number of times you wish
- hit play 
Then the song will play for that number for times till it's done then the next song plays as normal?

**Comment by Ngnintedem3004** [comment]
Yes 💯💯💯💯

**Comment by YBTopaz8** [comment]
Will be added tomorrow.
What happens when the user closes the app and relaunches? Should it continue playing x number of times until it's finished or should that rule be "discard" on each restart?

**Comment by Ngnintedem3004** [comment]
> when the user left  the app . In my opinion, the music should continue to turn in background witthout changing the configuration. So it continue playing x number of thé Times until it's finished

>When we close the app all things should be 
Discard .

> When we relaunch , we Can start  with the last state of the app or initialize all

**Comment by YBTopaz8** [comment]
Alright. Thanks. Will have it done by tomorrow.

I'm just trying to figure out how to add the UI for that lol.

**Comment by Ngnintedem3004** [comment]
WE believe in you ..

**Comment by YBTopaz8** [comment]
Added for Android and Windows 

https://github.com/user-attachments/assets/3d66c294-d2e0-4f8b-8c74-c2a2c1dd6adb


https://github.com/user-attachments/assets/5e870983-4e27-490a-9d51-a7b636acd49b
